---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adudumas/public_html/
    - /bin/cp cart.php $DEPLOYPATH
    - /bin/cp collection.php $DEPLOYPATH
    - /bin/cp detail_shoes.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp ajax.php $DEPLOYPATH
    - /bin/cp logout.php $DEPLOYPATH
    - /bin/cp register.php $DEPLOYPATH
    - /bin/cp shoes.php $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R controller $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R section $DEPLOYPATH
